trigger:
- docker-juice-shop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: wiz@0
  inputs:
    command: 'image'
    clientid: $(WIZ_CLIENT_ID)
    secret: $(WIZ_CLIENT_SECRET)
    succeedOnFailures: false
    policyHitsOnly: true
    image: 'd2dockerd2/juice-shop-wiz'
    scanPolicies: 'vuln-one-critical, vuln-two-high'
