trigger:
  - ist-azure-pipelines

pool:
  vmImage: 'ubuntu-latest'

steps:
  # BUILD Step: disabled for this POC, using pre-built image from DockerHub

  # - task: Docker@2
  #   displayName: Build Docker Image
  #   inputs:
  #     command: build
  #     Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
  #     repository: d2dockerd2/juice-shop-wiz
  #     tags: |
  #       testPush

  - task: CmdLine@2
    displayName: Pull Docker Image
    inputs:
      script: docker pull d2dockerd2/juice-shop-wiz:testPush

  # SCAN Step: Container Image
    # Wiz scans the image for vulnerabilities, secrets, malware, sensitive data, and EOL
    # Best practice to scan before Push Task (IF scan = success, THEN push to registry)
      # 'succeedOnFailures' should control scan gating (but has known inconsistencies)
        #   true  = scan reports findings but pipeline build continues (dev/POC)
        #   false = pipeline fails if Wiz CI/CD policies are violated (staging/prod)
          # 'continueOnError' is the ADO-native fallback option (remove for staging/prod where scan gating is enforced)
      # Use the 'policies' field to target specific Wiz CI/CD policies
  - task: wiz@1
    displayName: Wiz CLI - Container Image Scan
    # continueOnError: true
    inputs:
      serviceConnectionId: '70713e22-89e8-43df-85dc-411e1a172d5a' # Auth is handled by the Wiz service connection (Project Settings > Service Connections)
      command: 'scan'
      scanType: 'containerimage'
      image: 'd2dockerd2/juice-shop-wiz:testPush'
      driver: 'mount'
      sudo: true
      succeedOnFailures: true
      policies: 'Dev-Vulns-AuditOnly-Test'

  # SCAN Step: IaC + Directory (uncomment to scan repo files)
    # Wiz scans Dockerfiles, Terraform, etc. for misconfigs and secrets

  # - task: wiz@1
  #   displayName: Wiz CLI - IaC + Directories Scan
  #   inputs:
  #     serviceConnectionId: '70713e22-89e8-43df-85dc-411e1a172d5a'
  #     command: 'scan'
  #     scanType: 'dir'
  #     path: '.'
  #     succeedOnFailures: true
  #     # policies: 'vuln-one-medium' (targets a specific Wiz CI/CD policy instead of the defaults)

  # PUSH Step: (Disabled for POC, could push to ACR, DockerHub, etc.)

  # - task: Docker@2
  #   displayName: Push to Container Registry
  #   inputs:
  #     containerRegistry: 'AcrServiceConnection'
  #     command: push
  #     repository: juice-shop-wiz
  #     tags: |
  #       testPush

  # TAG Step:(Code-to-Cloud Correlation)
    # Wiz tags image with CI/CD metadata (git commit, repo, pipeline) to better trace containers to source code 
  - task: wiz@1
    displayName: Wiz CLI - Image Tag
    inputs:
      serviceConnectionId: '70713e22-89e8-43df-85dc-411e1a172d5a'
      command: 'tag'
      image: 'd2dockerd2/juice-shop-wiz:testPush'
      driver: 'mount'
      sudo: true