trigger:
  - ist-azure-pipelines

pool:
  vmImage: 'ubuntu-latest'

steps:
  # BUILD Step: disabled for this POC, using pre-built image from my DockerHub

  # - task: Docker@2
  #   displayName: Build Docker Image
  #   inputs:
  #     command: build
  #     Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
  #     repository: d2dockerd2/juice-shop-wiz
  #     tags: |
  #       testPush

  - task: CmdLine@2
    displayName: Pull Docker Image
    inputs:
      script: docker pull d2dockerd2/juice-shop-wiz:testPush

  # SCAN Step: Container Image
    # Wiz scans the image for vulnerabilities, secrets, malware, sensitive data, etc.
    # Best practice to scan before Push Task (IF scan = success, THEN push to registry)
      # Use the 'policies' field to target specific Wiz CI/CD policies. Policies control scan gating
        # 'byPolicyHits' controls what Wiz findings are shown at end of pipeline builds in ADO UI
          # Options: 'DISABLED' = shows all findings (good for non-prod envs), 'BLOCK' = shows findings that hit a Block Wiz policy (good for Prod pipelines)

  - task: wiz@1
    displayName: Wiz CLI - Container Image Scan
    inputs:
      serviceConnectionId: '70713e22-89e8-43df-85dc-411e1a172d5a' # Auth is handled by the Wiz service connection (Project Settings > Service Connections)
      command: 'scan'
      scanType: 'containerimage'
      image: 'd2dockerd2/juice-shop-wiz:testPush'
      driver: 'mount'
      sudo: true
      policies: 'IST-Dev-Vulns-AuditOnly-Test, Default sensitive data policy, Default secrets policy, Default malware policy'
      byPolicyHits: DISABLED

  # SCAN Step: IaC + Directory (uncomment to scan repo files)
    # Wiz scans Dockerfiles, Terraform, etc. for misconfigs and secrets

  # - task: wiz@1
  #   displayName: Wiz CLI - IaC + Directories Scan
  #   inputs:
  #     serviceConnectionId: '70713e22-89e8-43df-85dc-411e1a172d5a'
  #     command: 'scan'
  #     scanType: 'dir'
  #     path: '.'

  # PUSH Step: (Disabled for POC, could push to ACR, DockerHub, etc.)

  # - task: Docker@2
  #   displayName: Push to Container Registry
  #   inputs:
  #     containerRegistry: 'AcrServiceConnection'
  #     command: push
  #     repository: juice-shop-wiz
  #     tags: |
  #       testPush

  # TAG Step:(Code-to-Cloud Correlation)
    # Wiz tags image with CI/CD metadata (git commit, repo, pipeline) to better trace containers to source code

  - task: wiz@1
    displayName: Wiz CLI - Image Tag
    inputs:
      serviceConnectionId: '70713e22-89e8-43df-85dc-411e1a172d5a'
      command: 'tag'
      image: 'd2dockerd2/juice-shop-wiz:testPush'
      driver: 'mount'
      sudo: true