trigger:
  - ist-azure-pipelines

pool:
  vmImage: 'ubuntu-latest'

steps:
  # - task: Docker@2
  #   displayName: Build Docker Image
  #   inputs:
  #     command: build
  #     Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
  #     repository: d2dockerd2/juice-shop-wiz
  #     tags: |
  #       testPush

  - task: CmdLine@2
    displayName: Pull Docker Image
    inputs:
      script: docker pull d2dockerd2/juice-shop-wiz:testPush

# Scan Task Before Push Task (IF scan = success, THEN push to registry)
  - task: wiz@1
    displayName: Wiz CLI - Container Image Scan
    inputs:
      serviceConnectionId: '70713e22-89e8-43df-85dc-411e1a172d5a'
      command: 'scan'
      scanType: 'containerimage'
      image: 'd2dockerd2/juice-shop-wiz:testPush'
      driver: 'mount'
      succeedOnFailures: true
        # true = pipeline still succeeds when Wiz CI/CD policies / scan fail
        # false = pipeline gates on scan / policy results
      sudo: true

  # - task: Docker@2
  #   displayName: Push to Docker Hub
  #   inputs:
  #     containerRegistry: 'bb36d7a2-41db-4972-a5e7-05c91adc0732'
  #     command: push
  #     repository: juice-shop-wiz
  #     tags: |
  #       testPush

# Wiz tags image with CI/CD metadata to better trace containers to source code (Code-to-Cloud Correlation)
  - task: wiz@1
    displayName: Wiz CLI - Image Tag
    inputs:
      serviceConnectionId: '70713e22-89e8-43df-85dc-411e1a172d5a'
      command: 'tag'
      image: 'd2dockerd2/juice-shop-wiz:testPush'
      driver: 'mount'
      sudo: true